//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace index
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Bill()
        {
            this.Bill_Item = new HashSet<Bill_Item>();
        }
    
        public int id { get; set; }
        public string Table { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ICollection<Bill_Item> Bill_Item { get; set; }
    }
}
