//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace index
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public menu()
        {
            this.Bill_Item = new HashSet<Bill_Item>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual ICollection<Bill_Item> Bill_Item { get; set; }
    }
}
